script: |
  set -e

  cd /root/AQI/aqi-ml-prediction-krakow || { echo "Directory not found"; exit 1; }

  echo "Current dir:"
  pwd
  ls -la

  echo "Pulling latest code..."
  git pull origin main

  echo "Stopping old containers..."
  docker compose down

  echo "Cleaning unused Docker data..."
  docker system prune -f

  echo "Rebuilding containers..."
  docker compose up -d --build

  echo "Deploy done!"